### ISSUE TITLE
Implementing Access Restrictions

### ISSUE THREAD

**Issue by kazu23pole** [aws-solutions/workload-discovery-on-aws#22]
**Feature name**
Implementing Access Restrictions

**Is your feature request related to a problem? Please describe.**
It is password protected, but I can see configuration diagrams that may contain sensitive information from anywhere.

**Describe the feature you'd like to see implemented**
Add WAF.

**Comment by thebutler12** [comment]
Thanks for raising this. Could you please explain in a little more detail what you are seeing here? 

Is it that when you save a diagram you don't want to be able to make it available to your colleagues? If so, then saving as 'Private' will ensure only you can see it.

Is it the 'public' term that is the issue here? Any diagrams stored are only available to other users on your deployment of Perspective.

**Comment by kazu23pole** [comment]
Thanks for your reply.

I don't want to expose it to the outside Company.

As long as they can access CloudFront, there is a possibility of a brute force attack on Cognito authentication, so I thought it would be nice if we could restrict IPs.

**Comment by svozza** [comment]
We evaluated this request and it is not prioritised in the immediate roadmap for the solution.
