### ISSUE TITLE
Resource group based selection & dependency graphs

### ISSUE THREAD

**Issue by khan-asif** [aws-solutions/workload-discovery-on-aws#25]
**Feature name**
Dependency Graph for Resource Group

**Is your feature request related to a problem? Please describe.**
No. Enhancement needed on an existing feature.

**Describe the feature you'd like to see implemented**
On selecting Resource by Type (Tag), currently all resources are linked to the tag. Whereas it would be great to have that selection or other selections indicate relationship between child nodes. Example on selecting tag : Project = Portals, the diagram should display relationship between not just tag and services but also between services like Lambda and IAM role.

**Describe the value this feature will add to AWS Perspective**
Simplify selection of services and auto generate dependency graph for entire project / feature.

**Describe alternatives you've considered**
Selecting individual services, but this could run in hundreds.

**Comment by svozza** [comment]
So if I've got this right would you like to see the graph expand out more than one level as it does currently? I'm thinking we may keep the default behaviour as is because expanding multiple levels can become visually overwhelming very quickly but it could be very nice to have the option to pick how many levels out you want to expand when you right click on a resource.

**Comment by rakshb** [comment]
We've evaluated this request and added this to our backlog but it is not prioritized in the immediate roadmap for the solution.
