### ISSUE TITLE
Select all resources with specific tag

### ISSUE THREAD

**Issue by robeellocalised** [aws-solutions/workload-discovery-on-aws#549]
**Feature name**
Select all resources with a tag and create the diagram.

**Is your feature request related to a problem? Please describe.**
I have more than 10,000 resources fetched from AWS and they are not classified on the base of tags.

**Describe the feature you'd like to see implemented**
I want to create multiple diagrams on the basis of different tags.

**Describe the value this feature will add to AWS Perspective**
It'll help many organizations to classify their diagrams.

**Comment by shujacks** [comment]
Thanks for reaching out, we will add to our backlog for evaluation.

**Comment by svozza** [comment]
You can search for tags by typing the key name and value into the search bar joined with the `=` symbol. So for example if you have a tag with key `Enironment` and the value `prod` or `staging` you could do a search for `Environment=prod` or `Environment=staging`. You can tell which are tags because they'll have the resource type `AWS::Tags::tag`. If you select the checkbox for the tag(s) you want, any resources assoicated with the tag(s) will be added to a diagram when you choose the **Add to diagram** button.

<img width="1147" alt="Screenshot 2024-09-30 at 16 30 29" src="https://github.com/user-attachments/assets/091cb965-a3d9-41e4-84e6-49ccfe681162">
